"""
models.py — SQLAlchemy ORM models for God_View.

Tables
------
geospatial_events
    Stores ingested events that carry a geographic location.  Uses the
    PostGIS ``Geometry`` column type via GeoAlchemy2 so we can run
    spatial queries (ST_DWithin, ST_Intersects, etc.) directly in SQL.

system_alerts
    Stores alerts raised by ML workers or rule engines, optionally
    linked to a source geospatial event.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from geoalchemy2 import Geometry
from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    Uuid,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ------------------------------------------------------------------
# geospatial_events
# ------------------------------------------------------------------

class GeospatialEvent(Base):
    """An ingested event with a geographic location."""

    __tablename__ = "geospatial_events"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid, primary_key=True, default=uuid.uuid4
    )
    source: Mapped[str] = mapped_column(
        String(64), nullable=False, doc="Origin pipeline (gdelt, eonet, …)"
    )
    event_type: Mapped[str | None] = mapped_column(
        String(128), nullable=True, doc="E.g. wildfire, severe_storm, protest"
    )
    title: Mapped[str | None] = mapped_column(
        Text, nullable=True
    )
    description: Mapped[str | None] = mapped_column(
        Text, nullable=True
    )

    # --- Geography ---
    latitude: Mapped[float] = mapped_column(Float, nullable=False)
    longitude: Mapped[float] = mapped_column(Float, nullable=False)
    location: Mapped[str] = mapped_column(
        Geometry(geometry_type="POINT", srid=4326),
        nullable=False,
        doc="PostGIS Point derived from (longitude, latitude)",
    )
    country_code: Mapped[str | None] = mapped_column(
        String(8), nullable=True
    )
    region_name: Mapped[str | None] = mapped_column(
        String(256), nullable=True
    )

    # --- Metrics / scores ---
    severity: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="Normalised severity score 0-1"
    )
    goldstein_scale: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="GDELT Goldstein scale (-10 to +10)"
    )
    avg_tone: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="Average sentiment tone of coverage"
    )
    magnitude_value: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="E.g. earthquake magnitude, wind speed"
    )
    magnitude_unit: Mapped[str | None] = mapped_column(
        String(32), nullable=True
    )

    # --- Raw payload ---
    raw_payload: Mapped[dict | None] = mapped_column(
        JSONB, nullable=True, doc="Original ingested record as-is"
    )
    source_url: Mapped[str | None] = mapped_column(
        Text, nullable=True
    )

    # --- Timestamps ---
    event_ts: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, doc="When the event occurred"
    )
    ingested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    # --- Relationships ---
    alerts: Mapped[list["SystemAlert"]] = relationship(
        back_populates="event", cascade="all, delete-orphan"
    )

    # --- Indexes ---
    __table_args__ = (
        Index("ix_geospatial_events_source", "source"),
        Index("ix_geospatial_events_event_type", "event_type"),
        Index("ix_geospatial_events_country_code", "country_code"),
        Index("ix_geospatial_events_event_ts", "event_ts"),
        Index(
            "ix_geospatial_events_location",
            "location",
            postgresql_using="gist",
        ),
    )

    def __repr__(self) -> str:
        return (
            f"<GeospatialEvent id={self.id!s:.8} source={self.source!r} "
            f"type={self.event_type!r} lat={self.latitude} lon={self.longitude}>"
        )


# ------------------------------------------------------------------
# system_alerts
# ------------------------------------------------------------------

class SystemAlert(Base):
    """An alert generated by an ML model or rule engine."""

    __tablename__ = "system_alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid, primary_key=True, default=uuid.uuid4
    )
    alert_type: Mapped[str] = mapped_column(
        String(128), nullable=False,
        doc="E.g. anomaly_detected, threshold_breach, cluster_alert",
    )
    severity_level: Mapped[str] = mapped_column(
        String(32), nullable=False, default="info",
        doc="info | warning | critical",
    )
    title: Mapped[str] = mapped_column(
        String(512), nullable=False
    )
    message: Mapped[str | None] = mapped_column(
        Text, nullable=True
    )

    # --- Link to source event ---
    event_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid,
        ForeignKey("geospatial_events.id", ondelete="SET NULL"),
        nullable=True,
    )
    event: Mapped[GeospatialEvent | None] = relationship(
        back_populates="alerts"
    )

    # --- ML metadata ---
    model_name: Mapped[str | None] = mapped_column(
        String(128), nullable=True, doc="Name of the model that raised the alert"
    )
    model_version: Mapped[str | None] = mapped_column(
        String(64), nullable=True
    )
    confidence: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="Model confidence score 0-1"
    )
    details: Mapped[dict | None] = mapped_column(
        JSONB, nullable=True, doc="Arbitrary structured metadata"
    )

    # --- Status ---
    acknowledged: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )
    acknowledged_by: Mapped[str | None] = mapped_column(
        String(128), nullable=True
    )
    acknowledged_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # --- Timestamps ---
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    # --- Indexes ---
    __table_args__ = (
        Index("ix_system_alerts_alert_type", "alert_type"),
        Index("ix_system_alerts_severity_level", "severity_level"),
        Index("ix_system_alerts_event_id", "event_id"),
        Index("ix_system_alerts_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<SystemAlert id={self.id!s:.8} type={self.alert_type!r} "
            f"severity={self.severity_level!r}>"
        )
